{
  "hash": "2870cea2d288028511f6e9928819966f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"構造計算書\"\nsubtitle: \"鋼製単純梁 / 等分布荷重（サンプル）\"\ndate: 2026-09-12\ndate-format: \"YYYY年MM月DD日\"\n---\n\n\n# 計算概要・入力条件\n\n本書は、Quarto と Python による構造計算書作成のサンプルである。 等分布荷重を受ける鋼製単純梁について、線形弾性理論に基づく曲げ応力、 ウェブ中立軸のせん断応力、および最大たわみを計算し、設定した制限値と比較する。\n\n**検討範囲：** 強軸曲げ、微小変形、一定断面の Euler–Bernoulli 梁とする。 断面はフィレットを無視した対称 I 形とし、横座屈、局部座屈、接合部、 支点部の局部応力、振動およびせん断変形は対象外とする。 本書の OK は、以下に仮定した３項目の制限値に対する比較結果を表す。\n\n部材符号：**B-01**　／　断面呼称：**H\\-300 × 150 × 6\\.5 × 9**\n\n::: {#tbl-input .cell tbl-cap='入力条件（制限値はサンプル用の仮定値）' execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| 項目                     | 記号       | 値         | 単位   |\n|:-------------------------|:-----------|:-----------|:-------|\n| スパン                   | $L$        | 6,000      | mm     |\n| 梁せい                   | $h$        | 300        | mm     |\n| フランジ幅               | $b$        | 150        | mm     |\n| ウェブ厚                 | $t_w$      | 6.5        | mm     |\n| フランジ厚               | $t_f$      | 9          | mm     |\n| ヤング係数               | $E$        | 205,000    | N/mm²  |\n| 鋼材の単位体積重量       | $\\gamma$   | 78.5       | kN/m³  |\n| 固定荷重（梁自重を除く） | $w_G$      | 5          | kN/m   |\n| 積載荷重                 | $w_Q$      | 3          | kN/m   |\n| 曲げ応力の制限値         | $f_b$      | 156.7      | N/mm²  |\n| せん断応力の制限値       | $f_s$      | 90         | N/mm²  |\n| たわみの制限値           | $\\delta_a$ | L/300 = 20 | mm     |\n:::\n:::\n\n\n荷重はすべて鉛直下向きの線荷重とし、固定荷重・積載荷重・梁自重を係数 1.0 で加算する。 応力とたわみは同じ荷重ケースで計算する。内部計算は **N・mm** に統一し、 途中の計算値は丸めず、表示時のみ丸める。\n\n{{< pagebreak >}}\n\n# 解析モデル・断面性能\n\n左端をピン支持、右端をローラー支持とする。荷重は全スパンに一様に作用する。\n\n::: {.cell fig-height='2' fig-width='8' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![単純梁の支持・荷重条件と理想化した I 形断面](sample-beam_files/figure-typst/fig-model-output-1.svg){#fig-model fig-alt='左端がピン、右端がローラーの単純梁に下向き等分布荷重が作用する。右側に対称I形断面を示す。'}\n:::\n:::\n\n\nウェブ内法高さを $h_w = h - 2t_f$ とし、断面積 $A$、強軸の断面二次モーメント $I_x$、 弾性断面係数 $Z_x$ を次式により求める。市販形鋼の規格表に記載された断面性能とは区別する。\n\n$$\nA = 2bt_f + t_w h_w\n$$\n\n$$\nI_x = \\frac{bh^3-(b-t_w)h_w^3}{12}, \\qquad Z_x = \\frac{I_x}{h/2}\n$$\n\n中立軸より上側の断面一次モーメント $Q_0$ は、上フランジとウェブ上半分の和とする。\n\n$$\nQ_0 = bt_f\\left(\\frac{h}{2}-\\frac{t_f}{2}\\right)\n      + \\frac{t_w h_w}{2}\\frac{h_w}{4}\n$$\n\n::: {#tbl-section .cell tbl-cap='理想化断面の計算結果' execution_count=4}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| 項目               | 記号   | 計算値     | 単位   |\n|:-------------------|:-------|:-----------|:-------|\n| 断面積             | $A$    | 4,533.0    | mm²    |\n| 断面二次モーメント | $I_x$  | 69,325,191 | mm⁴    |\n| 弾性断面係数       | $Z_x$  | 462,167.9  | mm³    |\n| 断面一次モーメント | $Q_0$  | 261,038.25 | mm³    |\n:::\n:::\n\n\n{{< pagebreak >}}\n\n# 荷重・反力・断面力\n\n## 梁自重と荷重の組合せ\n\n断面積を mm² から m² に換算し、単位体積重量を乗じて梁自重 $w_s$ を求める。\n\n::: {.cell execution_count=5}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\nw_s = A\\times 10^{-6}\\gamma = 4533.0\\times10^{-6}\\times 78.5 = 0.355841\\;\\mathrm{kN/m}\n$$\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\nw = w_G+w_Q+w_s = 5+3+0.355841 = 8.355840\\;\\mathrm{kN/m}\n$$\n:::\n:::\n\n\n$1\\;\\mathrm{kN/m}=1\\;\\mathrm{N/mm}$ なので、$w$ の数値をそのまま N/mm として用いる。\n\n## 支点反力\n\n鉛直方向のつり合いと荷重の対称性より、両端の支点反力は等しい。\n\n::: {.cell execution_count=6}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\nR_A = R_B = \\frac{wL}{2} = \\frac{8.355840\\times 6000}{2} = 25.068\\;\\mathrm{kN}\n$$\n:::\n:::\n\n\n## 最大曲げモーメント・最大せん断力\n\n曲げモーメントはスパン中央で最大、せん断力の絶対値は支点の直内側で最大となる。\n\n::: {.cell execution_count=7}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\nM_{\\max} = \\frac{wL^2}{8} = \\frac{8.355840\\times 6000^2}{8} = 37.601\\;\\mathrm{kN\\,m}\n$$\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\nV_{\\max} = \\frac{wL}{2} = 25.068\\;\\mathrm{kN}\n$$\n:::\n:::\n\n\n左端からの距離を $x$ とすると、断面力の分布は次式で表される。 下縁引張となる曲げを正とし、せん断力の符号は以下の式に従う。\n\n$$\nV(x)=w\\left(\\frac{L}{2}-x\\right), \\qquad\nM(x)=\\frac{wx(L-x)}{2}\n$$\n\n{{< pagebreak >}}\n\n# 応力・たわみの検討\n\n## 曲げ応力\n\n弾性断面係数を用いて縁応力を求める。制限値 $f_b$ はこの例の入力値である。\n\n::: {.cell execution_count=8}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\n\\sigma_b = \\frac{M_{\\max}}{Z_x} = \\frac{37601282.2}{462167.9} = 81.36\\;\\mathrm{N/mm^2}\n$$\n:::\n:::\n\n\n## せん断応力\n\nウェブの中立軸で $\\tau=VQ/(It)$ を用いる。支点部の局部応力は含まない。\n\n::: {.cell execution_count=9}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\n\\tau_{\\max} = \\frac{V_{\\max}Q_0}{I_x t_w} = \\frac{25067.5\\times 261038.25}{69325191\\times 6.5} = 14.52\\;\\mathrm{N/mm^2}\n$$\n:::\n:::\n\n\n## 最大たわみ\n\n全荷重による曲げ変形のみを評価する。最大たわみはスパン中央に生じる。\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n$$\n\\delta_{\\max} = \\frac{5wL^4}{384EI_x} = 9.92\\;\\mathrm{mm}, \\qquad \\delta_a = \\frac{L}{300} = 20.00\\;\\mathrm{mm}\n$$\n:::\n:::\n\n\n## 検定一覧\n\n検定比は「計算値 ÷ 制限値」とし、丸め前の値が 1.0 以下なら OK とする。\n\n::: {#tbl-check .cell tbl-cap='設定した制限値に対する比較' execution_count=11}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| 検討項目           | 計算値   | 制限値   | 検定比   | 判定   |\n|:-------------------|:---------|:---------|:---------|:-------|\n| 曲げ応力 [N/mm²]   | 81.36    | 156.70   | 0.519    | OK     |\n| せん断応力 [N/mm²] | 14.52    | 90.00    | 0.161    | OK     |\n| たわみ [mm]        | 9.92     | 20.00    | 0.496    | OK     |\n:::\n:::\n\n\n**比較結果：全３項目が設定した制限値以内である。**\n\n{{< pagebreak >}}\n\n# 断面力図・変形図\n\n::: {.cell fig-height='4.9' fig-width='7.5' execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![せん断力・曲げモーメント・たわみの分布（たわみは下向きを正）](sample-beam_files/figure-typst/fig-response-output-1.svg){#fig-response fig-alt='せん断力は左端正から右端負へ直線的に変化し、曲げモーメントと下向きたわみは中央で最大となる対称分布。'}\n:::\n:::\n\n\n変形図は次の分布式から生成する。変形の表示倍率は実形状と異なる。\n\n$$\n\\delta(x)=\\frac{wx}{24EI_x}\\left(L^3-2Lx^2+x^3\\right)\n$$\n\n# 計算の追跡・適用範囲\n\n入力は `sample-beam.qmd` 冒頭の `BeamInput(...)` に集約し、計算式は `beam.py` に保持する。 本文中の計算値、検定表、図は同じ計算結果から生成し、出力のたびに再計算する。 `uv.lock` により使用する Python パッケージを固定する。\n\n本サンプルには、設計規準の選定や法令適合性の確認は含まれない。 実案件では、荷重条件、断面性能、材料定数、制限値および対象外の検討項目を、 当該案件の設計条件に合わせて整備する。\n\n",
    "supporting": [
      "sample-beam_files"
    ],
    "filters": [],
    "includes": {}
  }
}